- set_fact:
    nvidia_packages:
     - nvidia
     - nvidia-utils
     - lib32-nvidia-utils
     - nvidia-libgl
     - lib32-nvidia-libgl

- package:
    name: "{{ item }}"
    state: latest
  loop: "{{ nvidia_packages }}"

- debug:
    msg: "Vulkan is already installed as part of the 'nvidia' package."
  when: gpu_driver_vulkan_install
