# Following the instructions from:
# https://docs.fedoraproject.org/en-US/quick-docs/bumblebee/index.html
- name: Installing Nvidia packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - acpi
    - akmod-nvidia
    - dkms
    - kernel-devel
    - nvidia-driver

- name: Installing the Bumblebee repository
  shell: dnf -y copr enable chenxiaolong/bumblebee

- name: Installing Bumblebee
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - akmod-bbswitch
    - bumblebee
    - primus

- name: Allowing a user to use the "optirun" and "primusrun" commands
  user:
    name: "{{ gpu_driver_nvidia_bumblebee_user }}"
    groups: bumblebee
    append: yes
  when: gpu_driver_nvidia_bumblebee_user is defined

- name: Enabling Bumblebee
  systemd:
    name: bumblebeed
    enabled: yes

- name: Disallowing Nvidia to fallback to Nouveau
  systemd:
    name: nvidia-fallback
    masked: yes
    enabled: no

- name: Create bbswitch module configuration files
  file:
    path: "{{ item }}"
    state: touch
    mode: 0644
    owner: root
    group: root
  loop:
    - /etc/modules-load.d/bbswitch.conf
    - /etc/modprobe.d/bbswitch.conf

- name: Load the bbswitch module on boot
  lineinfile:
    path: /etc/modules-load.d/bbswitch.conf
    line: bbswitch

- name: Disable the Nvidia card on boot to save power
  lineinfile:
    path: /etc/modprobe.d/bbswitch.conf
    line: options bbswitch load_state=0 unload_state=1
